# Generated by Django 3.0.3 on 2020-02-22 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='X_test',
        ),
        migrations.RemoveField(
            model_name='index',
            name='X_train',
        ),
        migrations.RemoveField(
            model_name='index',
            name='y_test',
        ),
        migrations.RemoveField(
            model_name='index',
            name='y_train',
        ),
    ]
