# Generated by Django 3.0.3 on 2020-02-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_auto_20200222_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='save_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv', models.CharField(max_length=100)),
                ('X_train', models.BinaryField()),
                ('X_test', models.BinaryField()),
                ('y_train', models.BinaryField()),
                ('y_test', models.BinaryField()),
            ],
        ),
        migrations.DeleteModel(
            name='Download',
        ),
    ]
