# Generated by Django 3.0.3 on 2020-02-10 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='checkbox',
        ),
    ]
