# Generated by Django 3.0.3 on 2020-02-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_auto_20200222_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='end_date',
            field=models.CharField(default='2020-02-28', max_length=100),
        ),
    ]
