# Generated by Django 3.0.3 on 2020-02-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0004_auto_20200228_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='end_date',
            field=models.CharField(default='2020-02-29', max_length=100),
        ),
    ]
