# Generated by Django 3.0.3 on 2020-03-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0006_auto_20200317_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='end_date',
            field=models.CharField(default='2020-03-18', max_length=100),
        ),
    ]
