# Generated by Django 3.0.3 on 2020-03-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0007_auto_20200318_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pred',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('pred', models.FloatField()),
            ],
            options={
                'db_table': 'Pred',
                'managed': False,
            },
        ),
    ]
