# Generated by Django 2.2.7 on 2019-12-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_your_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('sender', models.EmailField(max_length=254)),
                ('cc_myself', models.BooleanField(default=True)),
            ],
        ),
    ]
