# Generated by Django 2.2.7 on 2019-12-18 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20191217_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default='2019-12-18'),
        ),
        migrations.CreateModel(
            name='completed_todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=200)),
                ('completed_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.TodoList')),
            ],
        ),
    ]
